#!/bin/sh

sequence() {
  local FIRST="$1"
  local LAST="$2"

  while [ "${FIRST}" -le "${LAST}" ]; do
    echo "${FIRST}"
    FIRST=$((FIRST + 1))
  done
}

for BACKGROUND in $(sequence 40 47) $(sequence 100 107) 49 ; do
  for FOREGROUND in $(sequence 30 37) $(sequence 90 97) 39 ; do
    for ATTRIBUTE in $(sequence 0 7) ; do
      # print the result
      printf "\033[${ATTRIBUTE};${BACKGROUND};${FOREGROUND}m %s \033[0m" \
        "[${ATTRIBUTE};${BACKGROUND};${FOREGROUND}m"
    done
    echo #newline
  done
done

exit 0
