#!/bin/bash

# Attribute codes:
# 00=none 01=bold 04=underscore 05=blink 07=reverse 08=concealed
# Text color codes:
# 30=black 31=red 32=green 33=yellow 34=blue 35=magenta 36=cyan 37=white
# Background color codes:
# 40=black 41=red 42=green 43=yellow 44=blue 45=magenta 46=cyan 47=white

for attribute in 00 01 04 05 07 08; do

  case "${attribute}" in
    00) printf '> none       | ' ;;
    01) printf '> bold       | ' ;;
    04) printf '> underscore | ' ;;
    05) printf '> blink      | ' ;;
    07) printf '> reverse    | ' ;;
    08) printf '> concealed  | ' ;;
  esac

  for color in {30..37}; do
    case "${color}" in
      30) printf "\e[${attribute};${color}m%s\e[0m " 'BLACK' ;;
      31) printf "\e[${attribute};${color}m%s\e[0m " 'RED' ;;
      32) printf "\e[${attribute};${color}m%s\e[0m " 'GREEN' ;;
      33) printf "\e[${attribute};${color}m%s\e[0m " 'YELLOW' ;;
      34) printf "\e[${attribute};${color}m%s\e[0m " 'BLUE' ;;
      35) printf "\e[${attribute};${color}m%s\e[0m " 'MAGENTA' ;;
      36) printf "\e[${attribute};${color}m%s\e[0m " 'CYAN' ;;
      37) printf "\e[${attribute};${color}m%s\e[0m " 'WHITE' ;;
    esac
  done

  printf '\n'

done
