#!/bin/sh

set -e

if test 0 -ne "$(id -u)"; then
    printf '%s: script needs to be run as root\n' "${0##*/}" >&2
    exit 1
fi

WEBSITE=https://dl.google.com/linux
KEY=$WEBSITE/linux_signing_key.pub
FILE=/etc/apt/sources.list.d/google-chrome.list

STRING="deb [arch=amd64] $WEBSITE/chrome/deb/ stable main"

wget -q -O - "$KEY" | apt-key add -
printf "%s\n" "$STRING" > "$FILE"
