#!/bin/sh

if test "$(id -u)" -gt 0; then
    printf 'E: %s\n' "script needs to be run as root" >&2
    exit 1
fi

wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
printf '%s\n' 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list
