#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	printf "E: Permission denied\n" >&2
	exit 1
fi

exec apt-get -y install \
	neovim \
	tmux \
	git \
	make \
    m4 \
    ffmpeg \
	curl \
    p7zip \
    p7zip-full \
    unar \
	mpv \
	keepassxc \
    gimp \
	qemu-system-x86 \
	libvirt-daemon \
	libvirt-clients \
	virt-manager \
	bridge-utils \
