#!/bin/sh

if test `id -u` -ne 0; then
	printf 'E: Permission denied\n' >&2
	exit 1
fi

exec apt-get -y install \
	tmux \
	vim \
	curl \
	git \
	make \
	p7zip-full \
	p7zip-rar \
	mpv \
	keepassxc \
	qemu-system-x86 \
	libvirt-daemon \
	libvirt-clients \
	virt-manager \
	bridge-utils \
