#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
    printf "E: Permission denied\n" >&2
    exit 1
fi

shift $#

set -- "$@" neovim tmux git make m4 ffmpeg curl                   # cli
set -- "$@" p7zip p7zip-full unar                                 # archive
set -- "$@" mpv keepassxc gimp                                    # gui
set -- "$@" qemu-system-x86 libvirt-daemon libvirt-clients        # virtual
set -- "$@" virt-manager bridge-utils

exec apt-get -y install "$@"
