#!/bin/sh

IFS='
'
while getopts n OPT; do
	case "$OPT" in
	(n) IFS=' ' ;;
	(:) printf 'E: option requires an argument -- %c\n' "$OPTARG" >&2; exit 1 ;;
	(\?) printf 'E: illegal argument -- %c\n' "$OPTARG" >&2; exit 1 ;;
	esac
done
shift $((OPTIND - 1))

for string; do
	shift 1

	case "$string" in
	(*\'*) ;;
	(*) set -- "$@" "'${string}'"; continue 1 ;;
	esac

	modified_string=\' character=

	until
		case "${#string}" in
		(0) true ;;
		(*) false ;;
		esac
	do
			character="${string%${string#?}}"
			string="${string#?}"

			case "$character" in
			(\') ;;
			(*) modified_string="${modified_string}${character}"; continue 1 ;;
			esac

			modified_string="${modified_string}'\\'"

			while
				case "${string%${string#?}}" in
				(\') true ;;
				(*) false ;;
				esac
			do
				string="${string#?}"
				modified_string="${modified_string}\\'"
			done

			modified_string="${modified_string}'"
	done

	modified_string="${modified_string}'"

	case "$modified_string" in
	("''\\'"*) modified_string="${modified_string#??}" ;;
	esac

	case "$modified_string" in
	(*"'''") modified_string="${modified_string%??}" ;;
	esac

	set -- "$@" "$modified_string"
done

case "$IFS" in
(' ') printf '%s' "$*" ;;
(*) printf '%s\n' "$*" ;;
esac
