#!/bin/sh

GITS="${HOME}/Git"
REPOS='
  https://github.com/godchurch/bash.git
  https://github.com/godchurch/c.git
  https://github.com/godchurch/dotfiles.git
  https://github.com/godchurch/py.git
  https://github.com/godchurch/random.git
  https://github.com/godchurch/sh.git
  https://github.com/godchurch/vm.git
'

if ! [ -d "${GITS}" ]; then
  mkdir --parent --verbose "${GITS}"
fi

for REPO in ${REPOS}; do
  BASE="${REPO##*/}" BASE="${BASE%*.git}"
  git clone ${REPO} ${GITS}/${BASE}
done
