#!/bin/sh
# The 'github.com/thameera/vimv' script but rewritten in sh.

set -e

if [ $# -eq 0 ]; then
    exec "$0" *
elif [ $# -eq 1 ]; then
    if [ \* = "$1" -a ! -e \* ]; then
        printf "%s: current directory is empty\n" "${0##*/}" 1>&2
        exit 1
    elif [ ! -e "$1" ]; then
        printf "%s: no such file or directory -- %s\n" "${0##*/}" "$1" 1>&2
        exit 1
    fi
else
    for pathname in "$@"; do
        if [ ! -e "$pathname" ]; then
            printf "%s: no such file or directory -- %s\n" "${0##*/}" "$pathname" 1>&2
            exit 1
        fi
    done
fi

if ! command -p -v mv > /dev/null; then
    printf "%s: command not found -- mv\n" "${0##*/}" 1>&2
    exit 1
elif ! command -p -v mkdir > /dev/null; then
    printf "%s: command not found -- mkdir\n" "${0##*/}" 1>&2
    exit 1
fi

IFS=' '
case "$*" in
    *'
'*) printf "%s: argument(s) contains a newline\n" "${0##*/}" 1>&2; exit 1 ;;
esac

pathnames="${TMPDIR:-/tmp}/${0##*/}.$$"
trap 'rm -f "$pathnames"' EXIT

printf "%s\n" "$@" > "$pathnames"
${EDITOR:-vi} "$pathnames"

pathnames_in=$# pathnames_out=0
while read -r output; do
    pathnames_out="$(($pathnames_out + 1))"
done < "$pathnames"

if [ "$pathnames_in" -ne "$pathnames_out" ]; then
    printf "%s: added/deleted lines\n" "${0##*/}" 1>&2
    exit 1
fi

renamed_pathnames=0
while read -r output; do
    if [ "$1" != "$output" ]; then
        set -- "$@" "$1" "$output"
        renamed_pathnames="$(($renamed_pathnames + 1))"
    fi
    shift 1
done < "$pathnames"

if [ "$renamed_pathnames" -eq 0 ]; then
    printf "%s: no filenames were changed\n" "${0##*/}" 1>&2
    exit 1
fi

until [ $# -eq 0 ]; do
    case "$2" in
        */*)
            if [ -n "${2%/*}" ] && [ ! -d "${2%/*}" ]; then
                command -p mkdir -p -- "${2%/*}"
            fi
            ;;
    esac
    command -p mv -- "$1" "$2"
    shift 2
done

printf "%s file(s) renamed.\n" "$renamed_pathnames"
