#!/bin/sh

pad_size ()
{
    while read -r SIZE NAME; do
        printf "%020d %s\n" "$SIZE" "$NAME"
    done
}
show_list ()
{
    while read -r SIZE NAME; do
        set -- "$@" "$NAME"
    done
    du -s --human-readable "$@"
}

du -s "$@" > /dev/null && du -s "$@" | pad_size | sort | show_list
