#!/bin/sh

Error ()
{
	format="E: ${1}\\n"
	shift 1
	printf "$format" "$@" >&2
	exit 1
}

effective_user_id="$(id -u 2> /dev/null)"
effective_user_id="${effective_user_id:-1000}"
test "$effective_user_id" -eq 0 || Error 'Permission denied'

command -v debootstrap > /dev/null || Error 'Missing dependency -- debootstrap'
command -v sfdisk > /dev/null || Error 'Missing dependency -- sfdisk'
command -v debian-chroot > /dev/null || Error 'Missing dependency -- debian-chroot'

case $# in
(0) Error 'Missing device operand' ;;
(1) code_name="$(lsb_release -sc)" || Error 'Unable to get code_name operand' ;;
(*) Error 'Extra operands specified' ;;
esac

device="$1"
partition="${device}1"

build_directory="/target"

set -x
set -e

sfdisk -f "$device" << EndOfFile
2048,
EndOfFile
sfdisk -f --part-type "$device" 1 83
sfdisk -f -A "$device" 1
mkfs.ext4 "$partition"

mkdir -p "$build_directory"
mount "$partition" "$build_directory"
debootstrap --arch amd64 "$code_name" "$build_directory"

AWK='BEGIN{ printf "network:\n  version: 2\n  renderer: %s\n  ethernets:", "networkd" }
/^[0-9]+/ && $2 != "lo:" { printf "\n    %s\n      dhcp4: true", $2 }'

block_device_attributes="$(blkid --probe --output export "$partition")"
unset UUID TYPE
eval "$block_device_attributes"
test -n "$UUID"
test -n "$TYPE"

formated_ip="$(ip link show)"
formated_ip="$(printf '%s' "$formated_ip" | awk "$AWK")"

fstab="UUID=$UUID / $TYPE errors=remount-ro 0 1
tmpfs /tmp tmpfs nosuid,nodev 0 0"
hostname="ubuntu"
hosts="127.0.0.1    localhost
127.0.1.1    $hostname"
apt_sources="\
deb http://archive.ubuntu.com/ubuntu/ ${code_name} main restricted
deb http://archive.ubuntu.com/ubuntu/ ${code_name}-updates main restricted
deb http://archive.ubuntu.com/ubuntu/ ${code_name} universe
deb http://archive.ubuntu.com/ubuntu/ ${code_name}-updates universe
deb http://archive.ubuntu.com/ubuntu/ ${code_name} multiverse
deb http://archive.ubuntu.com/ubuntu/ ${code_name}-updates multiverse
deb http://archive.ubuntu.com/ubuntu/ ${code_name}-backports main restricted universe multiverse
# deb http://archive.canonical.com/ubuntu ${code_name} partner
deb http://security.ubuntu.com/ubuntu ${code_name}-security main restricted
deb http://security.ubuntu.com/ubuntu ${code_name}-security universe
deb http://security.ubuntu.com/ubuntu ${code_name}-security multiverse"

mkdir -p "$build_directory/etc/netplan"
printf '%s\n' "$formated_ip" > "$build_directory/etc/netplan/01-netcfg.yaml"
mkdir -p "$build_directory/etc/apt"
printf '%s\n' "$apt_sources" > "$build_directory/etc/apt/sources.list"
printf '%s\n' "$fstab" > "$build_directory/etc/fstab"
printf '%s\n' "$hostname" > "$build_directory/etc/hostname"
printf '%s\n' "$hosts" > "$build_directory/etc/hosts"

LC_ALL=C debian-chroot "$build_directory" /bin/sh -c "
set -x
set -e
apt-get update
apt-get install -y linux-image-generic linux-headers-generic grub-pc build-essential
apt-get dist-upgrade -y
apt-get autoremove -y
apt-get clean -y
grub-install --target=i386-pc \"$device\"
update-grub"
