#!/bin/bash

set -e

end () { printf "E: $1\n"; exit 1; } >&2

ID="$(id -u)"
[ "$ID" -eq 0 ] || end "permission denied"

command -v debootstrap > /dev/null || end "'debootstrap' not installed"
command -v sfdisk > /dev/null || end "'sfdisk' not installed"
command -v arch-chroot > /dev/null || end "'arch-chroot' not installed"

[ $# -eq 0 ] && end "missing device operand"
[ $# -ge 2 ] && end "too many operands"

CODE="$(lsb_release -sc)" || end "unable to get codename operand"
RELEASE="$(lsb_release -sr)" || end "unable to get release operand"

DEVICE="${1%/}"
PART="${DEVICE}1"
TARGET="/target"

echo "type=83, bootable" | sfdisk "$DEVICE"
mkfs.ext4 "$PART"

mkdir -p "$TARGET"
mount "$PART" "$TARGET"
debootstrap --arch=amd64 "$CODE" "$TARGET"

UUID="$(blkid -s UUID -o value "$PART")"
TYPE="$(blkid -s TYPE -o value "$PART")"
echo "UUID=$UUID / $TYPE errors=remount-ro 0 1" > "$TARGET/etc/fstab"
echo "tmpfs /tmp tmpfs nosuid,nodev 0 0">> "$TARGET/etc/fstab"

echo "ubuntu" > "$TARGET/etc/hostname"

LINK_A="http://archive.ubuntu.com/ubuntu/"
LINK_S="http://security.ubuntu.com/ubuntu/"
REPO="main restricted universe multiverse"
mkdir -p "$TARGET/etc/apt"
echo "deb $LINK_A $CODE $REPO" > "$TARGET/etc/apt/sources.list"
echo "deb $LINK_A $CODE-updates $REPO" >> "$TARGET/etc/apt/sources.list"
echo "deb $LINK_A $CODE-backports $REPO" >> "$TARGET/etc/apt/sources.list"
echo "deb $LINK_S $CODE-security $REPO">> "$TARGET/etc/apt/sources.list"

mkdir -p "$TARGET/etc/netplan"
echo "network:" > "$TARGET/etc/netplan/01-network-manager-all.yaml"
echo "  version: 2" >> "$TARGET/etc/netplan/01-network-manager-all.yaml"
echo "  renderer: NetworkManager" >> "$TARGET/etc/netplan/01-network-manager-all.yaml"

arch-chroot "$TARGET" apt-get update
arch-chroot "$TARGET" apt-get upgrade
arch-chroot "$TARGET" apt-get install ubuntu-standard "linux-generic-hwe-$RELEASE" build-essential
arch-chroot "$TARGET" apt-get autoremove
arch-chroot "$TARGET" apt-get clean
arch-chroot "$TARGET" grub-install --target=i386-pc "$DEVICE"
arch-chroot "$TARGET" update-grub
