#!/bin/bash

set -e

end () { printf "E: $1\n"; exit 1; } >&2

ID="$(id -u)"
[ "$ID" -eq 0 ] || end "permission denied"

command -v debootstrap > /dev/null || end "'debootstrap' not installed"
command -v sfdisk > /dev/null || end "'sfdisk' not installed"
command -v arch-chroot > /dev/null || end "'arch-chroot' not installed"

[ $# -eq 0 ] && end "missing device operand"
[ $# -ge 2 ] && end "too many operands"

CODE="$(lsb_release -sc)" || end "unable to get codename operand"
RELEASE="$(lsb_release -sr)" || end "unable to get release operand"

DEVICE="${1%/}"
TARGET="/target"

echo "type=83, bootable" | sfdisk "$DEVICE"
mkfs.ext4 "${DEVICE}1"

mkdir -p "$TARGET"
mount "${DEVICE}1" "$TARGET"
debootstrap --arch=amd64 "$CODE" "$TARGET"

UUID="$(blkid -s UUID -o value "${DEVICE}1")"
TYPE="$(blkid -s TYPE -o value "${DEVICE}1")"
cat > "$TARGET/etc/fstab" << EOF
UUID=$UUID / $TYPE errors=remount-ro 0 1
tmpfs /tmp tmpfs nosuid,nodev 0 0
EOF

cat > "$TARGET/etc/hostname" << EOF
ubuntu
EOF

cat > "$TARGET/etc/hosts" << EOF
127.0.0.1    localhost
127.0.1.1    ubuntu
EOF

mkdir -p "$TARGET/etc/apt"
cat > "$TARGET/etc/apt/sources.list" << EOF
deb http://archive.ubuntu.com/ubuntu/ ${CODE} main restricted
deb http://archive.ubuntu.com/ubuntu/ ${CODE} universe multiverse
deb http://archive.ubuntu.com/ubuntu/ ${CODE}-updates main restricted
deb http://archive.ubuntu.com/ubuntu/ ${CODE}-updates universe multiverse
deb http://archive.ubuntu.com/ubuntu/ ${CODE}-backports main restricted
deb http://archive.ubuntu.com/ubuntu/ ${CODE}-backports universe multiverse
deb http://security.ubuntu.com/ubuntu ${CODE}-security main restricted
deb http://security.ubuntu.com/ubuntu ${CODE}-security universe multiverse
EOF

ETHER="$(ip addr | sed -n 's/^[0-9]\{1,\}: \{1,\}\(enp[[:alnum:]]\{1,\}\):.*$/\1/p')"
mkdir -p "$TARGET/etc/netplan"
cat > "$TARGET/etc/netplan/99_config.yaml" << EOF
network:
  version: 2
  renderer: networkd
  ethernets:
    $ETHER:
      dhcp4: true
EOF

arch-chroot "$TARGET" apt-get update
arch-chroot "$TARGET" apt-get -y upgrade
arch-chroot "$TARGET" apt-get -y install ubuntu-standard "linux-generic-hwe-$RELEASE"
arch-chroot "$TARGET" apt-get -y autoremove
arch-chroot "$TARGET" apt-get clean
arch-chroot "$TARGET" grub-install --target=i386-pc "$DEVICE"
arch-chroot "$TARGET" update-grub
