#!/bin/sh

set -e

for dep in pulseaudio pactl; do
	command -v "$dep" >/dev/null && continue 1
	printf 'Program "%s" not found. Please install it.\n' "$dep" >&2
	exit 1
done

if ! pulseaudio --check; then
	printf "E: Pulseaudio is not running.\n" >&2
	exit 1
fi

info="`pactl info`"
default_sink="`printf '%s\n' "$info" \
	| sed -n 's/^Default[[:blank:]]\{1,\}Sink:[[:blank:]]\{1,\}\(.*\)$/\1/p'`"
default_source="`printf '%s\n' "$info" \
	| sed -n 's/^Default[[:blank:]]\{1,\}Source:[[:blank:]]\{1,\}\(.*\)$/\1/p'`"

case "$1" in
	sink)
		test -n "$default_sink"

		case "$2" in
			up) pactl set-sink-volume "$default_sink" +5% ;;
			down) pactl set-sink-volume "$default_sink" -5% ;;
			mute) pactl set-sink-mute "$default_sink" toggle ;;
			*) ;;
		esac
		;;
	source)
		test -n "$default_source"

		case "$2" in
			up) pactl set-source-volume "$default_source" +5% ;;
			down) pactl set-source-volume "$default_source" -5% ;;
			mute) pactl set-source-mute "$default_source" toggle ;;
			*) ;;
		esac
		;;
	*)
		test -n "$default_sink"
		test -n "$default_source"

		pactl set-sink-volume "$default_sink" 50%
		pactl set-sink-mute "$default_sink" 0
		pactl suspend-sink "$default_sink" 0

		pactl set-source-volume "$default_source" 0%
		pactl set-source-mute "$default_source" 1
		pactl suspend-source "$default_source" 0
		;;
esac
