#!/bin/bash

waitingPrompt()
{
    declare -- index=''
    declare -a array=(
        "●ooooooooooo"
        "o●oooooooooo"
        "oo●ooooooooo"
        "ooo●oooooooo"
        "oooo●ooooooo"
        "ooooo●oooooo"
        "oooooo●ooooo"
        "ooooooo●oooo"
        "oooooooo●ooo"
        "ooooooooo●oo"
        "oooooooooo●o"
        "ooooooooooo●"
        "oooooooooo●o"
        "ooooooooo●oo"
        "oooooooo●ooo"
        "ooooooo●oooo"
        "oooooo●ooooo"
        "ooooo●oooooo"
        "oooo●ooooooo"
        "ooo●oooooooo"
        "oo●ooooooooo"
        "o●oooooooooo"
    )

    while true
    do
        for index in "${array[@]}"
        do
            printf "\r%s" "${index}"
            sleep 0.2
        done
    done
}

doStuff()
{
    waitingPrompt &

    declare -i int
    declare -i waitPid="${!}"

    for ((int=0; int<10; int++ )); do sleep 1; done

    kill "${waitPid}"
    printf "\n"
}

doStuff

exit 0
